package com.sjp.mmall.dao;

import com.sjp.mmall.pojo.Pay_info;
import com.sjp.mmall.pojo.Pay_infoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Pay_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    long countByExample(Pay_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    int deleteByExample(Pay_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    int insert(Pay_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    int insertSelective(Pay_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    List<Pay_info> selectByExample(Pay_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Pay_info record, @Param("example") Pay_infoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 18 16:17:50 CST 2019
     */
    int updateByExample(@Param("record") Pay_info record, @Param("example") Pay_infoExample example);
}